# -*- coding: utf-8 -*-

table_content = """# Tabela de Controle e Registro de Correções do PPC

Esta tabela registra o histórico consolidado de apontamentos, revisões da equipe, pareceres da Biblioteca/DEPE e as respectivas correções implementadas no documento oficial do PPC (Técnico em Administração Integrado — IFSC Garopaba).

---

## 📊 Tabela Consolidada de Correções (Seção V — Estrutura Curricular)

| N | SEÇÃO | ITEM | PÁG | REVISOR | DESCRIÇÃO DO PROBLEMA | SUGESTÃO DE CORREÇÃO | DEVOLUTIVA DA CORREÇÃO | STATUS |
| :-: | :--- | :--- | :-: | :--- | :--- | :--- | :--- | :-: |
| **1** | Subitem V.3.1 (Ementa 7) | Notação de Semestres (LPL Ano 1) | p. 18 | ANDRE LUIZ SILVA DE MORAES | Rasura no documento docente indicando "1º e 1º semestre" para a UC de Língua Portuguesa — Ano 1. | Decodificação e correção para "1º e 2º semestres" (Ano 1, 80h anuais), mantendo a proporcionalidade do curso. | Corrigido no .tex e .md para 1º e 2º semestres, garantindo 80h anuais da formação geral. | **Concluído** |
| **2** | Subitem V.2.2 & V.3.2 (Ementa 36) | Matriz Curricular (Matemática p/ Adm) | p. 7 / p. 48 | ANDRE LUIZ SILVA DE MORAES | UC "Matemática para Administração" (40h) posicionada erroneamente na tabela do 1º Ano da Formação Geral. | Realocação da UC para a tabela do 2º Ano (3º semestre / Formação Específica) em sintonia com a matriz de referência. | Realocada na matriz para o 3º semestre (Ano 2) na Formação Técnica Específica. | **Concluído** |
| **3** | Subitem V.2.4 | Cálculo de Subtotais e Síntese da Matriz | p. 6-11 | ANDRE LUIZ SILVA DE MORAES | Subtotal de Formação Geral do 1º Ano estava calculado como 840h em vez de 880h, propagando erro na síntese final. | Recálculo do subtotal (880h) e atualização da síntese: Formação Geral (2.280h), Técnica (680h), Politécnico (240h), Total 3.200h. | Valores recalculados e síntese perfeitamente balanceada em 3.200h totais. | **Concluído** |
| **4** | Subitem V.3 | Bibliografia Fantasma / Truncada | p. 12-68 | ANDRE LUIZ SILVA DE MORAES | Inserção de linhas fantasma ("3º título pendente") na Bibliografia Complementar em UCs com menos de 3 obras na fonte. | Remoção dos placeholders excedentes nas tabelas TeX, espelhando estritamente os títulos reais existentes na fonte. | Placeholders removidos; bibliografias espelham estritamente o acervo validado. | **Concluído** |
| **5** | Subitem V.3.1 | Desmembramento de UCs (Formação Geral) | p. 12-68 | ANDRE LUIZ SILVA DE MORAES | Quantitativo de blocos ementários divergente da matriz (Espanhol sem desmembramento por ano; Geografia/História desalinhadas). | Desmembramento de Espanhol em 2 blocos (Ano 1/2), Geografia em 2 blocos (Ano 1/3) e História em 2 blocos (Ano 2/3), alinhando a matriz para 45 UCs. | Matriz estruturada em 45 tabelas ementárias anuais alinhadas à matriz curricular. | **Concluído** |
| **6** | Sumário (\\tableofcontents) | Sumário PDF e Navegação Interativa | p. 1 | ANDRE LUIZ SILVA DE MORAES | O sumário do PDF compilado (\\tableofcontents) não permitia o clique direto para saltar até as seções e ementas. | Configuração do pacote hyperref (hypersetup) na classe ifsc-ppc.cls, ativando hiperlinks no sumário e bookmarks no PDF. | Hiperlinks ativados no PDF para todas as seções e ementas do curso. | **Concluído** |
| **7** | Subitem V.2 & V.3 | Alinhamento de Semestres (Física, Química, Gestão de Operações, Biologia) | p. 6-11, 12-68 | ANDRE LUIZ SILVA DE MORAES | Ambiguidade de redação nos semestres das ementas (Física III constando como 4º/5º, Química II como 2º/3º, Química III como 1º, Gestão de Operações como 4º/5º e Biologia 3 como 1º/2º). | Correção dos cabeçalhos para os semestres reais: Física III (5º/6º sem - 80h), Química II (3º/4º sem - 80h), Química III (5º sem - 40h), Gestão de Operações (3º/4º sem - 80h) e Biologia 3 (5º/6º sem - 80h). | Cabeçalhos de semestres e CHs totalmente harmonizados com a matriz por anos. | **Concluído** |
| **8** | Subitem V.2.3 & V.3.3 | Consolidação da Oficina de Integração I e Carga Horária da Oficina II | p. 7, p. 11, p. 55 | ANDRE LUIZ SILVA DE MORAES | Duplicidade de documento ementário para Oficina de Integração I ("Ano 2" e "Semestre 4 e 5"); e Oficina II constando com 80h na matriz do 3º Ano. | Descarte do bloco duplicado e consolidação da Oficina I em ementa única de 80h no Ano 2 (3º/4º sem); e atualização da CH da Oficina II para 160h no Ano 3 (5º/6º sem). | Bloco duplicado excluído; Oficina I consolidada em 80h e Oficina II em 160h no 3º ano. | **Concluído** |
| **9** | Subitem V.3 | Ordenação Cronológica do Ementário (Alinhamento com a Matriz Curricular) | p. 12-68 | ANDRE LUIZ SILVA DE MORAES | As ementas visuais estavam agrupadas por disciplina (ex: Artes 1 e 2 juntas, LPL 1, 2 e 3 juntas), divergindo da ordem da Matriz Curricular Detalhada por Anos. | Reordenação sequencial exata das 45 ementas no .tex e .md seguindo o 1º Ano (Ementas 1–17), 2º Ano (Ementas 18–33) e 3º Ano (Ementas 34–45). | Ementário reordenado sequencialmente de 1 a 45 por ano letivo e semestre. | **Concluído** |
| **10** | Subitem V.3.1 (Ementas 3 e 20) | Ementário (Inglês Anos 1 e 2) | p. 14, p. 28 | ANDRE LUIZ SILVA DE MORAES | Pendência de preenchimento dos Objetivos, Conteúdos, Metodologia e Bibliografias nas 2 UCs de Inglês. | Inclusão integral das ementas enviadas no Markdown master e no arquivo .tex oficial. | Ementas completas inseridas e sem parágrafos espúrios de avaliação. | **Concluído** |
| **11** | Subitem V.3.1 (Ementas 4, 21 e 34) | Ementário (LPL Anos 1, 2 e 3 — Proff. Karyna e Sandra) | p. 15, p. 29, p. 50 | ANDRE LUIZ SILVA DE MORAES | Validação dos conteúdos, 10h de CH Prática e referências bibliográficas atualizadas das 3 UCs de Língua Portuguesa e Literatura. | Consolidação integral e conferência nos arquivos .tex e .md master com compilação limpa do PDF. | Ementas de LPL 1, 2 e 3 consolidadas com conteúdos e acervo ABNT completo. | **Concluído** |
| **12** | Subitem V.3.2 (Ementa 31) | Ementário (Empreendedorismo I — Diretrizes IFSC) | p. 46 | ANDRE LUIZ SILVA DE MORAES | Pendência de preenchimento dos Objetivos, Conteúdos com temáticas transversais, Metodologia (LINEDS/PBL) e Bibliografias NBR 6023. | Inclusão completa da ementa com modelo Business Model Canvas, temáticas transversais obrigatórias e acervo bibliográfico. | Atualizada posteriormente com a ementa autoral definitiva da Profa. Fabiana (Tab. 31). | **Concluído** |
| **13** | Subitem V.3.2 (Auditoria Geral) | Ementário Geral (45 UCs) | pp. 12–56 | ANDRE LUIZ SILVA DE MORAES | Presença de marcadores pendentes e ausência de Objetivos/Conteúdos nas UCs de Geografia I/III, Marketing I/II e Gestão Financeira. | Preenchimento e saneamento de 100% das 45 UCs do ementário, eliminando todos os pendentes e compilando o PDF oficial. | 100% das 45 UCs preenchidas, sem pendências e com compilação limpa. | **Concluído** |
| **14** | Subitem V.3.1 (Ementa 8) | Ementário (Matemática Ano 1 — Formatação) | p. 19 | ANDRE LUIZ SILVA DE MORAES | Falha de formatação com asteriscos residuais (*Parte I...**) e desalinhamento de numeração bibliográfica. | Correção para comandos nativos TeX (\\textbf{}) no código .tex e inclusão de marcadores de tópicos no Markdown master. | Formatação nativa TeX corrigida sem asteriscos residuais. | **Concluído** |
| **15** | Subitem V.3.1 (Ementário Geral) | Ementário (Remoção de Numeração Manual e Notas) | pp. 8–95 | ANDRE LUIZ SILVA DE MORAES | Presença de numeração sequencial (1., 2.) nas referências e nota interna editorial de confirmação de ementa. | Remoção da numeração sequencial de todas as bibliografias e exclusão da nota editorial em Responsabilidade Socioambiental. | Numerações manuais removidas de todas as referências bibliográficas. | **Concluído** |
| **16** | V – ESTRUTURA CURRICULAR DO CURSO | Ementário das UCs (Bibliografias Básica e Complementar — ABNT) | pp. 11–101 | BIBLIOTECA / ANDRE LUIZ SILVA DE MORAES | Inconsistências ABNT NBR 6023 nas ementas: (1) subtítulos de obras em negrito após dois pontos; (2) iniciais de autores capturadas na tag de negrito; (3) ausência de itálico na expressão et al.. | Padronização ABNT NBR 6023 em todas as 283 referências das 45 UCs: negrito restrito exclusivamente ao título principal (subtítulo normal após ':'); correção das iniciais de autores; itálico aplicado estritamente à locução et al.. | Padronização ABNT NBR 6023 aplicada a todas as referências do documento. | **Concluído** |
| **17** | TODAS AS SEÇÕES (I A X) | Estrutura e Nomenclatura das Seções (Modelo Oficial IFSC) | pp. 1–106 | ANDRE LUIZ SILVA DE MORAES | Divergências na nomenclatura de títulos, numeração de seções e omissão dos subitens 15 (Outras características do egresso) e 21 (Atividade em EaD) em relação ao modelo oficial do IFSC. | Reestruturação integral com 100% de fidelidade ao modelo oficial do Google Docs: 10 Macroseções Romanas (I a X), 30 Subitens Arábicos Contínuos (1 a 30), inclusão dos subitens 15 e 21 e títulos padronizados. | Documento TeX reestruturado em 10 Seções Romanas e 30 Subitens Oficiais. | **Concluído** |
| **18** | Subitem V.18.1 | Matriz Curricular Resumida (Distribuição por Blocos) | p. 8 | ANDRE LUIZ SILVA DE MORAES | Tabela excedendo a margem direita da página (Overfull hbox de 83.8pt) devido ao uso de tabular rígido sem delimitação de largura. | Substituição por ambiente tabularx com largura delimitada em \\linewidth, tipografia \\small e aplicação do padrão visual institucional (ifscgreen e cinzaTabela). | Tabela convertida para tabularx ajustada perfeitamente à largura da página. | **Concluído** |
| **19** | Subitem V.18.3 (Ementário 45 UCs) | Sincronização de Fidelidade das Ementas com o Acervo Docente | pp. 12–106 | ANDRE LUIZ SILVA DE MORAES / CLAUDE AUDIT | Divergências de fidelidade literal em relação aos Google Docs preenchidos pelos docentes: (1) 4 UCs críticas preenchidas com textos provisórios (Marketing I, Marketing II, Empreendedorismo I e Gestão Financeira); (2) semestres e CH de Gestão Financeira (6º sem / 40h); (3) resumos em objetivos/metodologias e referências espúrias de Matemática em Filosofia. | Sincronização integral 1:1: (1) Substituição total do conteúdo das 4 UCs críticas pelo texto oficial dos docentes; (2) Correção de Gestão Financeira para 5º e 6º semestres e 80h; (3) Expansão de objetivos literais (Ed. Física 1 e 2, Biologia 1 e 3, Física 1, 2 e 3, Química 1, 2 e 3); (4) Remoção de referências espúrias em Filosofia; (5) Preservação de Geografia conforme pendência de confirmação. | Substituição integral efetuada nas 4 UCs críticas, CH de Gestão Financeira corrigida para 80h (5º/6º sem) e acervo 100% sincronizado. | **Concluído** |
| **20** | Seção IV & V (Subitens 10 a 16 e 17) | Validação dos Subitens 10 a 16 e Sanitização Textual da Metodologia | pp. 6–8, 10 | JACQUELINE NARCISO BASTOS / ANDRE LUIZ SILVA DE MORAES | Dúvida sobre atualização dos textos dos Subitens 10 a 16 com os arquivos da Profa. Fabiana (proponente) e necessidade de revisão dos dados/modelos novos. | Confirmação de que os textos dos Subitens 10 a 16 já constituem a versão consolidada e disponibilizada pela Profa. Fabiana na etapa prévia. Aplicação de ajuste editorial na Metodologia (Subitem 17), saneando menção contextual residual e alinhando à formação integrada de Administração. | Documento atualizado. Os textos dos Subitens 10 a 16 correspondem à versão consolidada com a Profa. Fabiana. A Metodologia (Subitem 17) foi revisada e saneada para 100% de aderência ao curso de Administração. | **Concluído** |
| **21** | Seção V (Estrutura Curricular) | Subitem 17 (Metodologia de Desenvolvimento Pedagógico) | p. 8 | JACQUELINE NARCISO BASTOS | Dúvida: o texto que está no item 17 foi copiado do PPC anterior? Está estranho. | Esclarecer a origem do texto do Subitem 17 e validar a pertinência da fundamentação pedagógica com a comissão. | Não foi copiado do PPC anterior. O texto do Subitem 17 foi construído para atender à Resolução CONSUP 142/2025, trazendo a fundamentação da Pedagogia Histórico-Crítica (Saviani), a concepção de omnilateralidade e a metodologia de Ciclos Temáticos (Silva, 2016) para as Oficinas de Integração I e II (Núcleo Politécnico Comum). O texto foi revisado e saneado para a área de Administração. | **Concluído** |
| **22** | Seção V (Estrutura Curricular) | Subitem 21 (Atividade em EaD) | p. 104 | JACQUELINE NARCISO BASTOS | Dúvida: no PPC antigo havia observação sobre a possibilidade de porcentagem de 10% em EaD. Não será mais incluído? | Reintroduzir a redação que prevê a possibilidade regulamentar de até 10% de atividades mediadas por tecnologia (AVA Moodle), conforme o RDP do IFSC. | Ajustado no texto. Mantida a definição de curso presencial (0h de EaD fixa na matriz), porém com a inclusão da cláusula regulamentar do RDP/IFSC que faculta o desenvolvimento de até 10% da carga horária das UCs em atividades não presenciais mediadas pelo AVA Moodle. | **Concluído** |
| **23** | Seção V & VI (Subitens 23, 24 e 25) | Atendimento ao Discente, Aproveitamento de Conhecimentos e Avaliação | pp. 104–105 | JACQUELINE NARCISO BASTOS | Não estão no PDF os textos do PPC antigo. Está resumido de uma forma estranha (Subitens 23 e 24). | Restaurar o texto completo e detalhado do Câmpus Garopaba e do RDP para Atendimento ao Discente (Coordenadoria Pedagógica, PEDi, NAE/AEE, PAEVS), Aproveitamento de Conhecimentos e Avaliação da Aprendizagem. | Texto completo restaurado. Substituído o resumo preliminar pela redação institucional integral do Câmpus Garopaba e do RDP, detalhando a atuação da Coordenadoria Pedagógica, concessão de PEDi (Plano de Estudo Diferenciado), NAE/AEE para Educação Especial, PAEVS, os critérios regimentais de validação de saberes/aproveitamento de estudos e as diretrizes completas de avaliação formativa e recuperação paralela. | **Concluído** |
"""

with open('base-de-conhecimento/tabela_de_correcoes_ppc.md', 'w', encoding='utf-8') as f:
    f.write(table_content)

print("Tabela consolidada de correções atualizada com os itens 21, 22 e 23!")
